### ISSUE TITLE
add support for custom tags

### ISSUE THREAD

**Issue by chen23** [f5devcentral/terraform-aws-bigip-module#11]
Currently it is not possible to specify custom tags for either the aws instance and/or the interfaces.  This is necessary in environments that require custom tagging and for the use of the Cloud Failover Extension.  It should be possible to specify custom tags by interface.

**Comment by papineni87** [comment]
Tracking internally with InfraANO-375

**Comment by yossi-r** [comment]
Ran into the same issue
