### ISSUE TITLE
Does not install Telemetry Streaming

### ISSUE THREAD

**Issue by codygreen** [f5devcentral/terraform-aws-bigip-module#18]
The variable file contains a variable for the specified version of Telemetry Streaming but the f5_onboard.tmpl does not install Telemetry Streaming.

**Comment by nmenant** [comment]
Tracking this internally with INFRAANO-162

**Comment by RavinderReddyF5** [comment]
Issue fixed in v0.9.1,try with latest master

**Comment by papineni87** [comment]
Issue is fixed in latest release v0.9.1, please reopen this issue if you see it again
