### ISSUE TITLE
f5-onboard.tmpl running AS3 sample on default depoyment

### ISSUE THREAD

**Issue by codygreen** [f5devcentral/terraform-aws-bigip-module#19]
it looks like any deployment of the terraform-aws-bigip-module will execute the AS3 declaration referenced in the f5_onboard.tmpl  https://github.com/f5devcentral/terraform-aws-bigip-module/blob/1cdc497cdcd14f7fa2779ac08f7901e76384fa85/f5_onboard.tmpl#L59

This should only happen in the test harness or when leveraging the examples.  A default deployment of the module should not configure sample virtual servers.

**Comment by nmenant** [comment]
tracking this internally with INFRAANO-160

**Comment by papineni87** [comment]
Issue is fixed in latest release v0.9.1, please reopen this issue if you see it again

**Comment by RavinderReddyF5** [comment]
Issue fixed in v0.9.1,try with latest master
