### ISSUE TITLE
Variable Consistency for FAST URL 

### ISSUE THREAD

**Issue by codygreen** [f5devcentral/terraform-aws-bigip-module#22]
ATC component variable names should be consistent.  All other ATC components have a format of *package_URL*.   The FastPackageUrl variable should mimic this.

https://github.com/f5devcentral/terraform-aws-bigip-module/blob/1cdc497cdcd14f7fa2779ac08f7901e76384fa85/variables.tf#L144

**Comment by nmenant** [comment]
Thanks. Tracking this internally with INFRAANO-152. Will look into it for all our BIG-IP modules

**Comment by RavinderReddyF5** [comment]
Issue fixed in v0.9.1,try with latest master
