### ISSUE TITLE
provider version requirements 

### ISSUE THREAD

**Issue by yossi-r** [f5devcentral/terraform-aws-bigip-module#25]
The current provider version requirements are locked on older versions, aws is locked at 3.8 and the newest release is 3.25 
since it's locked, when using the module it forces the old version and prevents me from using a new version of the provider (which i need for other resources) 
do you actually need to lock the version of the AWS provider? if not please change the version requirement. if you do please consider upgrading.

**Comment by nmenant** [comment]
Tracking this internally with INFRAANO-175

**Comment by RavinderReddyF5** [comment]
Issue fixed in v0.9.1,try with latest master
