### ISSUE TITLE
private ip addresses 

### ISSUE THREAD

**Issue by yossi-r** [f5devcentral/terraform-aws-bigip-module#29]
trying to understand the output of private_addresses
for a 2-nic deployment i get the following:
    "private_addresses" = [
      toset([
        "100.64.203.56",
        "100.64.203.74",
      ]),
    ]

how can i consistently get the value of the primary ip address of a specific interface? 
i think output should be a map based on the name of the interface with a clear distinction of what is a primary vs secondary

**Comment by papineni87** [comment]
Tracking with InfraANO-374

**Comment by mjmenger** [comment]
The unordered set response makes it impossible to consistently retrieve the primary addresses of the BIG-IP nics.
