### ISSUE TITLE
bigip_aws_3nic_deploy: only deploys 2nic

### ISSUE THREAD

**Issue by chen23** [f5devcentral/terraform-aws-bigip-module#3]
When you deploy bigip_aws_3nic_deploy you end up with a bigip that only has 2nics, not 3:

![image](https://user-images.githubusercontent.com/63689/101052232-613f5e80-3554-11eb-966a-81d57cc9ac7e.png)

**Comment by RavinderReddyF5** [comment]
@chen23 Thanks for Reporting issues, we identified fix and validating commit, will let u know once it is done.

**Comment by GaddamSaketha** [comment]
Hi @chen23 
We have committed the fix to master branch. Can you please try the latest code and  let us know if the issue still persists

**Comment by curtkersey** [comment]
I was working with @chen23 on this, and I tested the fix.  I can see 3 network interfaces via AWS console now --

![image](https://user-images.githubusercontent.com/2438670/101171029-38c76b00-360d-11eb-931b-d338b822a356.png)

**Comment by RavinderReddyF5** [comment]
Issue fixed in v0.9.1,try with latest master
