### ISSUE TITLE
remove instance count from the module 

### ISSUE THREAD

**Issue by yossi-r** [f5devcentral/terraform-aws-bigip-module#30]
starting version 0.13 terraform supports the 'count' meta argument for modules 
https://www.terraform.io/docs/language/meta-arguments/count.html

using the argument when calling a module is a lot simpler and makes more sense in terms of the way terraform builds resources. 
please remove the count from the module and include examples of how to use count when calling the module

**Comment by RavinderReddyF5** [comment]
@yossi-r , i think if you are looking for how to use `count` with module, we provided same here: https://github.com/f5devcentral/terraform-aws-bigip-module/blob/master/examples/bigip_aws_1nic_deploy/main.tf#L187

for now we providing this using instance_count variable [ default 1], if you dont provide count argument also it defaults to 1.

**Comment by RavinderReddyF5** [comment]
closing this issue , as it already have example for module count
