### ISSUE TITLE
Unable to deploy 1nic setup. 

### ISSUE THREAD

**Issue by f5killer** [f5devcentral/terraform-aws-bigip-module#37]
Code is failing. Some where it is hard cored to selected "ap-south-1" reason.

Error: Error creating ENI: InvalidParameterValue: user 054166279988 does not own a resource subnet_id_mgmt
        status code: 400, request id: d172449f-7640-4578-ac59-f207953142e7

  on ../../main.tf line 218, in resource "aws_network_interface" "mgmt1":
 218: resource "aws_network_interface" "mgmt1" {

**Comment by RavinderReddyF5** [comment]
@f5killer , we have input in https://github.com/f5devcentral/terraform-aws-bigip-module/blob/master/examples/bigip_aws_1nic_deploy/terraform.tfvars for ap-south-1, its user changeable parameter

**Comment by f5killer** [comment]
what about error 

Error: Error creating ENI: InvalidParameterValue: user 054166279988 does not own a resource subnet_id_mgmt
status code: 400, request id: d172449f-7640-4578-ac59-f207953142e7

**Comment by RavinderReddyF5** [comment]
@f5killer is your subnet created in different region ? than we mentioned in example. 
if you just use make use of our example, it will create sunets in the region we provide through tfvars.

https://github.com/f5devcentral/terraform-aws-bigip-module/blob/master/examples/bigip_aws_1nic_deploy/main.tf#L139

**Comment by RavinderReddyF5** [comment]
@f5killer i did test now , and don't run into any issues.

**Comment by papineni87** [comment]
@f5killer  It looks like permission issue, can you try in any other region where you can deploy ?

**Comment by RavinderReddyF5** [comment]
@f5killer closing this issue, please open new if you have any other issue
