### ISSUE TITLE
bigip_aws_3nic_deploy: passwd reported in TF output does not match AWS Secrets Manager passwd

### ISSUE THREAD

**Issue by curtkersey** [f5devcentral/terraform-aws-bigip-module#5]
When running using the default settings (outside of region and prefer) in repo, the value reported by TF output for bigipuser password and the value shown in AWS Secrets Manager are different.  The value that works for bigipuser is the one that TF reports in output.  I have not tried other examples.

**Comment by RavinderReddyF5** [comment]
@curtkersey By default this module uses dynamic generated password instead AWS Secrets Manager. if we want to enable enable AWS secret manager we should provide: "aws_secretmanager_auth" as "true", and "aws_secretmanager_secret_id" input parameters to module

**Comment by curtkersey** [comment]
Ok. Are the plans to integrate the repo with the necessary calls for AWS Secrets Manager?  It is a bit confusing for users to see two passwords.  I would recommend updating documentation if Secrets Manager is not going to be used.

**Comment by nmenant** [comment]
We are missing documentation to highlight the two different approach and how to use each. We will update our documentation to address this. This is tracked internally with INFRAANO-47

**Comment by RavinderReddyF5** [comment]
Issue fixed in v0.9.1,try with latest master
