### ISSUE TITLE
No way to taint bigip AMI image

### ISSUE THREAD

**Issue by mwardbopp** [f5devcentral/terraform-aws-bigip-module#59]
I can't figure out a way to taint a BIGIP, so that I upgrade the underlying AMI image. I'm not sure if this is because there isn't a resource I can reference or an issue because count is being used. Any help would be appreciated!

When using aws_instance to create this, taint/in-place upgrade is straight forward.

resource "aws_instance" "f5" {
  ami           = data.aws_ami.f5_ami.id
  instance_type = "t2.medium"
  key_name      = aws_key_pair.demo.key_name
  user_data     = data.template_file.f5_init.rendered

terraform taint aws_instance.f5

**Comment by RavinderReddyF5** [comment]
Hi @mwardbopp if you want to upgrade is it not possible to provide variable `f5_ami_search_name` with new image you looking to module?

**Comment by mwardbopp** [comment]
Perfect, that works great.
