### ISSUE TITLE
custom_user_data as required field is a breaking change

### ISSUE THREAD

**Issue by mjmenger** [f5devcentral/terraform-aws-bigip-module#60]
when switching from module version 0.9.4 to 0.9.6, the custom_user_data attribute is listed as required and breaks builds that do not require custom_user_data.

Steps to reproduce:
 - select a Terraform project that works with a previous version of the AWS BIG-IP module
 - change module source reference from a previous version to 0.9.6
 - run Terraform apply

Expected Result:
 - creates the same result when using previous module versions

Actual Result:
 - error message indicating that custom_user_data is a required attribute

**Comment by papineni87** [comment]
@mjmenger  I overlooked the variable and by passing default value as null in variable section resolves the issue. I will push the fix for it

**Comment by mjmenger** [comment]
v 0.9.7 passes my tests 👍
