### ISSUE TITLE
using aws_secretsmanager_secret does not actually keep a secret

### ISSUE THREAD

**Issue by chen23** [f5devcentral/terraform-aws-bigip-module#7]
The way that the module is written it is exporting the bigip_password value into the AWS metadata service.  Ideally this should be replaced with using f5-bigip-runtime-init to avoid this problem.

## Details

Starting here: https://github.com/f5devcentral/terraform-aws-bigip-module/blob/master/main.tf#L411

The value is used for the template here: https://github.com/f5devcentral/terraform-aws-bigip-module/blob/master/f5_onboard.tmpl#L16

That template value can be viewed either from the VM or via the AWS console (not good)

![image](https://user-images.githubusercontent.com/63689/101513021-ae06a900-3949-11eb-95dc-f8201763ffb0.png)

## Recommendation

Instead f5-bigip-runtime-init should be uses that fetches the value from the BIG-IP itself using credentials that the BIG-IP is granted.  
https://github.com/F5Networks/f5-bigip-runtime-init/blob/9a2979fa58bac06829ad91373efc4488f51c1b75/src/lib/cloud/aws/cloudClient.ts#L90

Here is an example (not tested) of using it with AWS secrets manager: 
https://github.com/F5Networks/f5-bigip-runtime-init/blob/main/examples/config/example_4.yaml

**Comment by nmenant** [comment]
We are transitioning on leveraging bigip-runtime-init with our BIG-IP modules. We will make sure this is addressed

INFRAANO-49 is the internal ID for this

**Comment by RavinderReddyF5** [comment]
Issue fixed in v0.9.1,try with latest master
